lxc_vmid: 110
lxc_hostname: bergen-ai

lxc_template: local:vztmpl/debian-13-standard_13.6-1_amd64.tar.zst

lxc_storage: local-zfs
lxc_rootfs_size: 100

lxc_memory: 16384
lxc_swap: 2048
lxc_cores: 8

lxc_bridge: vmbr2

lxc_ip: dhcp
lxc_ip6: dhcp

lxc_unprivileged: true
lxc_onboot: true

lxc_firewall: 1

lxc_ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
lxc_root_password: "{{ vault_lxc_root_password }}"

pve_node: venombox
pve_inventory_host: venombox

lxc_gpu:
  enabled: true

  host_path: /dev/dri
  container_path: /dev/dri

  video_host_gid: 44
  render_host_gid: 993

  video_container_gid: 44
  render_container_gid: 992

ollama_enable_vulkan: true
ollama_enable_igpu: true

###############################################################################
# LDAP
###############################################################################

ldap_enabled: true

ldap_server_label: "Bergen OpenLDAP"
ldap_host: bergen.intern
ldap_port: 389

ldap_use_tls: false
ldap_validate_cert: false

ldap_base_dn: dc=bergen,dc=intern
ldap_search_base: cn=users,dc=bergen,dc=intern

ldap_username_attribute: uid
ldap_mail_attribute: mail
ldap_search_filter: "(objectClass=inetOrgPerson)"

# Synology erlaubt derzeit anonyme LDAP-Suchen.
ldap_bind_dn: ""
ldap_bind_password: ""
