---
galaxy_info:
  role_name: evcc
  author: Bergen Platform
  description: Install and operate EVCC on a dedicated Debian LXC
  license: UNLICENSED
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
