---
- name: Validate EVCC role variables
  ansible.builtin.import_tasks: validate_vars.yml

- name: Install EVCC
  ansible.builtin.import_tasks: install.yml

- name: Prepare EVCC persistent directories
  ansible.builtin.import_tasks: directories.yml

- name: Configure EVCC service
  ansible.builtin.import_tasks: service.yml

- name: Validate EVCC service
  ansible.builtin.import_tasks: validate.yml
