---
- name: Create container directories

  ansible.builtin.file:

    path: "{{ item }}"

    state: directory

    owner: root

    group: ai

    mode: "2775"

  loop:

    - "{{ podman_storage_root }}"

    - "{{ podman_storage_root }}/openwebui"

    - "{{ podman_storage_root }}/postgres"

    - "{{ podman_storage_root }}/redis"

    - "{{ podman_storage_root }}/anythingllm"

    - "{{ podman_storage_root }}/searxng"
