---
- import_tasks: validate.yml
- import_tasks: install.yml
- import_tasks: persistence.yml
- import_tasks: tls.yml
- import_tasks: secrets.yml
- import_tasks: configure.yml
- import_tasks: service.yml
- import_tasks: api.yml
